### ISSUE TITLE
RGB colors are not translated correctly

### ISSUE THREAD

**Issue by sedrubal** [pycontribs/ansi2html#128] opened 2021-04-09 08:31 UTC
Using this example file: [`cyan.txt`](https://github.com/pycontribs/ansi2html/files/6284288/cyan.txt)

```bash
$ cat cyan.txt | ansi2html --inline
```

Produces a random color and does not use the original one (cyan `#9bf6ff`):

```html
<span style="color: #afff5f">I am cyan (#9bf6ff)</span>
```

For latex the same wrong color is used:

```bash
cat tmp | ansi2html --inline --latex
```

```latex
\textcolor[HTML]{afff5f}{I am cyan (#9bf6ff)}
```

**Comment by sedrubal** [comment] 2021-04-09 08:32
This might be a duplicate of #101

**Comment by ssbarnea** [comment] 2021-04-14 06:31
If you have a passing PR, ping me.

**Comment by ziegenberg** [comment] 2021-10-30 17:42
This is a duplicate of #101. Ansi2html currently does not support `truecolor` codes. I'd suggest closing this issue in favor of #101.

**Closed** 2021-11-02 10:47 UTC
